# -*- coding: utf-8 -*-
from content_helpers import publish, section, p, ul, cards, table, terms, trust_links, SAFETY
from content_products import product_cards

CATEGORIES = [
("/dog-toys/","Wholesale Natural Dog Toys from Vietnam","Dog Toys","dog-chewing-coffeewood.jpg",
 "Build a wholesale dog-toy assortment around coffee wood, coconut fiber and hemp. Compare play types, sample-approved sizes and private-label packaging with a Vietnam manufacturer.",
 ["coffee-wood-dog-chew","coconut-fiber-dog-ball","hemp-rope-dog-toy"],
 [("Chew toys","Wood stick specifications and responsible chew-range planning.","/dog-toys/chew-toys/"),
 ("Rope & tug toys","Define length, knots and attachment checks.","/dog-toys/rope-toys/"),
 ("Fetch & balls","Compare diameter, construction and pack format.","/dog-toys/fetch-toys/"),
 ("Enrichment","Texture-led formats and development briefs.","/dog-toys/puzzle-toys/")],
 [("Coffee wood","Hard chew format","Size, surface, cracks and a conservative use label"),
 ("Coconut fiber","Supervised fetch and carry","Diameter, winding, loose fiber and internal components"),
 ("Hemp fiber","Supervised interactive play","Knot security, fraying and any rope connections")],
 "Start with a narrow assortment that has a clear role at shelf: a wood chew, a fetch ball and an interactive rope. For each, specify the intended dog size and play context. Add more designs after sample evaluation and actual sell-through data."),
("/dog-toys/chew-toys/","Natural Dog Chews Wholesale","Dog Toys","winvn-coffee-wood-sizes.png",
 "Source non-edible natural dog chew toys led by coffee wood sticks. Compare reference sizes, review use limitations and approve the product specification before placing a wholesale order.",
 ["coffee-wood-dog-chew"],[],
 [("Standard stick","Single wood component","Confirm size and composition"),
 ("Wood with rope","Multi-component toy","Confirm both materials and connection security"),
 ("Private-label pack","Brand-specific presentation","Size guide, warnings and pack protection")],
 "This category covers chew toys, not edible treats. Harder does not automatically mean safer or better for strong chewers. Select a range only after reviewing sample construction and clear supervised-use instructions. Coffee wood collection information supports supplier selection; the product page carries the detailed size table."),
("/dog-toys/rope-toys/","Rope & Tug Dog Toys Wholesale","Dog Toys","winvn-hemp-wood-assortment.jpg",
 "Discuss natural-fiber rope, knotted and ball-with-rope designs for supervised tug play. Specify fiber identity, rope geometry and packaging for wholesale or private-label orders.",
 ["hemp-rope-dog-toy","hemp-fiber-ball"],[],
 [("Knotted rope","Length, diameter, knots","Inspect knot security and fraying"),
 ("Ball with rope","Ball and handle geometry","Assess the connection as a separate part"),
 ("Wood with rope","Wood and rope specification","Agree component and attachment checks")],
 "Hemp, cotton and coconut fiber are different materials; confirm the exact fiber or blend in the selected design. A catalogue photo is not proof of reinforcement or measured pull strength. Define any test method and acceptance criteria before using a strength claim on packaging."),
("/dog-toys/fetch-toys/","Natural Fetch & Ball Dog Toys Wholesale","Dog Toys","dog-coconut-balls-lifestyle.jpg",
 "Compare coconut-fiber and hemp balls for a supervised fetch-and-carry assortment. Approve diameter, weight, surface and packing before committing to volume.",
 ["coconut-fiber-dog-ball","hemp-fiber-ball"],[],
 [("Coir ball","Texture and winding","Confirm diameter and any core"),
 ("Hemp ball","Wound-fiber construction","Confirm the three catalogue size references"),
 ("Multi-pack","Assortment and carton","Check every component and sold-as-set label")],
 "A natural-fiber ball is not a rubber ball with a different appearance. Do not assume bounce, flotation, weather resistance or a fixed lifespan. The ball must be too large to swallow whole, and the chosen sample should be assessed for the intended style of supervised play."),
("/dog-toys/puzzle-toys/","Natural Enrichment Dog Toys Wholesale","Dog Toys","winvn-hemp-wood-assortment.jpg",
 "Explore texture-led natural toys and discuss enrichment designs for your range. Current products emphasize material and shape; treat new treat-dispensing mechanisms as custom development.",
 ["hemp-rope-dog-toy","hemp-fiber-ball"],[],
 [("Knotted forms","Handling and supervised interaction","Define geometry and intended use"),
 ("Mixed textures","Range variety","Declare every component"),
 ("New mechanisms","OEM/ODM feasibility","Prototype, test and approve before claiming availability")],
 "This is an enrichment sourcing category, not a claim that the displayed products are tested food puzzles. If you need a treat dispenser or measured difficulty levels, submit a specific brief. Agree cleaning, moving-part and food-contact requirements with the appropriate specialists for that construction."),
("/cat-toys/","Wholesale Natural Cat Toys","Cat Toys","cat-loofah-toys-lifestyle.jpg",
 "Build a cat-toy range from coconut-fiber balls and loofah shapes. Compare construction, shape-specific dimensions and private-label packaging for international retail.",
 ["coconut-fiber-cat-ball","loofah-cat-toy"],
 [("Balls & chasers","Choose a cat-specific size and construction.","/cat-toys/balls/"),
 ("Catnip & play shapes","Optional filling and attachment requirements.","/cat-toys/catnip-toys/")],
 [("Coconut-fiber balls","Batting and chasing","Check size and loose fiber"),
 ("Loofah shapes","Lightweight play","Check stitching and detachable parts"),
 ("Optional catnip","Development request","Confirm inclusion, source and labeling")],
 "A cat assortment needs its own specifications rather than scaled-down dog-toy descriptions. Ask for each shape's measurements and every internal or attached component. Plan pack information around supervised play, inspection and replacement, without promising dental or therapeutic benefits."),
("/cat-toys/balls/","Natural Cat Balls & Chasers Wholesale","Cat Toys","winvn-coconut-fiber-balls.jpg",
 "Request coconut-fiber cat-ball samples and build a measured, consistent batting-and-chasing range with your own tags or packaging.",
 ["coconut-fiber-cat-ball"],[],
 [("Single ball","Diameter and mass","Approve a cat-specific sample"),
 ("Ball set","Quantity and size mix","Check individual and outer labeling"),
 ("Retail carton","Units and dimensions","Confirm master-carton packing")],
 "Specify the diameter, mass and finished texture rather than selecting from S/M/L alone. Check winding and any core or binding thread. A mixed-size photo is a range reference, not evidence that all sizes suit cats."),
("/cat-toys/catnip-toys/","Loofah Shapes & Catnip Options Wholesale","Cat Toys","winvn-loofah-play-shapes.png",
 "Source loofah play shapes and discuss optional catnip-filled designs. Confirm filling, seams and labeling for each selected SKU.",
 ["loofah-cat-toy"],[],
 [("Unfilled shape","Loofah and attachments","Confirm dimensions and seams"),
 ("Catnip option","Optional inclusion","Approve filling specification and source"),
 ("Custom silhouette","OEM/ODM development","Review detachable parts and feasibility")],
 "Catnip is not included in every toy. State clearly whether a quoted SKU is unfilled or contains catnip, and confirm the amount and source when relevant. A custom shape requires its own sample and component list."),
("/collections/aggressive-chewers/","Sourcing Toys for Strong Chewers: Limits & Options","Materials","dog-chewing-coffeewood.jpg",
 "Evaluate strong-chewer requests carefully. No natural toy is indestructible, and hard wood is not automatically suitable for forceful chewing.",
 ["coffee-wood-dog-chew","hemp-rope-dog-toy"],[],
 [("Hard chew","Tooth and fracture risks","Seek veterinary guidance on suitability"),
 ("Rope play","Fraying and ingestion risks","Use only for supervised interaction"),
 ("Claims","No indestructible promise","Describe tested construction, not guaranteed outcomes")],
 "Do not use XL or XXL as a blanket answer for every power chewer. Mouth size, chewing behavior and dental health matter, and increasing size does not remove the risks of hard chewing. Retail copy should acknowledge limits rather than promising safe failure or swallowable fibers."),
("/collections/teething-puppies/","Puppy Toy Sourcing: Size & Material Considerations","Materials","dog-lifestyle-chew-1.jpg",
 "Plan puppy-focused ranges with particular care around developing teeth, detachable parts and size. Small dimensions alone do not make a hard chew puppy-safe.",
 [],[],
 [("Age and dental stage","Individual suitability","Obtain veterinary advice"),
 ("Toy construction","Attachments and loose fibers","Approve a species-appropriate design"),
 ("Labeling","Supervision and replacement","Avoid universal puppy-safe claims")],
 "Do not automatically recommend coffee wood XS/S for teething puppies. Discuss a puppy-specific design, intended age range and professional suitability assessment. A loofah material reference can inform development, but an existing cat SKU is not a validated puppy product."),
("/collections/plastic-free/","Pet Toys for a Plastic-Free Sourcing Brief","Materials","winvn-natural-toy-assortment.png",
 "Explore coffee wood, coconut fiber, hemp and loofah options, then verify the complete product and packaging composition before using a plastic-free claim.",
 ["coffee-wood-dog-chew","coconut-fiber-dog-ball","hemp-fiber-ball","loofah-cat-toy"],[],
 [("Product body","Headline natural material","Check cores, thread, glue and coatings"),
 ("Retail packaging","Paper or kraft options","Check laminates, inks and windows"),
 ("Shipping protection","Bags and desiccants","Do not describe vacuum film as plastic-free")],
 "Natural, renewable, upcycled and biodegradable describe different properties. Coffee wood and coconut husks can support specific reuse stories; hemp and loofah should not automatically be called waste-derived. Whole-product disposal claims need evidence for the selected construction and conditions."),
]

def build(root):
    for path,h1,active,img,lede,products,subcategories,comparison,notes in CATEGORIES:
        puppy_link=p('Planning a young-dog range? Review <a href="/collections/teething-puppies/">puppy-toy sourcing and suitability considerations</a>.') if path=="/dog-toys/" else ""
        references=product_cards(products) if products else p('No puppy-specific SKU has been confirmed in the supplied specification. Use the <a href="/materials/">material overview</a> to discuss a dedicated design; do not relabel a cat toy or hard wood stick as puppy-safe.')
        parts=[section("Plan the assortment",p(notes)+(cards(subcategories,2) if subcategories else "")+puppy_link),
               section("Product references for your brief",references,True),
               section("Materials, formats and buying checks",table(["Option","What to specify","What to check"],comparison)),
               section("Wholesale terms: MOQ, samples and lead time",terms(),True),
               section("Private label, quality and export preparation",
                 p("Send quantities per SKU, destination country, intended sales channel and required launch date. Standard designs with your branding are quoted differently from new constructions. Separate product quantity from the minimum for printed boxes.")+
                 p('Explore <a href="/services/private-label-pet-toys/">private-label options</a> or <a href="/services/oem-odm-pet-toy-manufacturing/">OEM/ODM development</a>. For recurring assortments, use our <a href="/services/wholesale-pet-products/">wholesale service</a>.')+trust_links()),
               section("Clear use instructions belong on every pack",p(SAFETY)+p('Review <a href="/guides/pet-toy-safety-testing-requirements/">how to scope product testing</a> and <a href="/sustainability/">how material claims are qualified</a>.'),True)]
        publish(root,path,h1+" | WINVN",lede,h1,lede,parts,active=active,image="/assets/img/"+img,
            faqs=[("Can I start with a small mixed order?", "Ask for a line-by-line quote. A minimum starting from 50 pcs applies only to selected standard products, not automatically to the whole assortment or every custom design."),
                  ("Can the products carry my brand?", "Yes, discuss labels, tags, packaging and wood engraving where suitable. Approve artwork and the physical sample before production."),
                  ("What does the quotation need to include?", "Product references, dimensions, quantities per SKU, branding, packaging, destination, timing and any buyer testing or document requirements.")])
