# -*- coding: utf-8 -*-
from content_helpers import publish, section, p, ul, table, cards, terms, trust_links, SOURCE_OEM, AMAZON
from content_products import product_cards

SOLUTIONS = [
("amazon-sellers","Amazon Sellers","Amazon FBA Pet Product Supplier | Private Label | VietPaw",
 "Private-Label Natural Pet Toys for Amazon FBA Sellers",
 "Develop a natural-material range with pack dimensions, buyer-supplied barcode artwork and a marketplace-specific preparation brief. Confirm the product, costs and shipment plan before production.",
 "warehouse-winvn-boxes.jpg",
 [("A differentiated assortment","Compare coffee wood, coir, hemp and loofah around a defined use and customer, not a guaranteed ranking or profit claim."),
 ("A measured retail pack","Confirm unit dimensions and weight after packaging, not just the bare toy."),
 ("Shipment preparation","Provide the current marketplace, unit/set rules, barcode files, carton labels and assigned destination."),
 ("Product quality","Approve sizes, construction and a QC plan; reviews and marketplace acceptance cannot be guaranteed.")],
 [("Product cost","Quoted unit price, branding, packaging and any development/test costs"),
 ("Logistics","Inbound freight, duties, destination handling and delivery arrangements"),
 ("Amazon fees","Referral, fulfillment, storage and other applicable program charges"),
 ("Sales costs","Advertising, returns, refunds and promotion assumptions")],
 "A single-item SKU and an assortment box have different retail prices, fulfillment costs and conversion behavior. Test contribution margin and sell-through, not average order value alone. A higher order value is not proof of higher profit or a reason to remove a two-pack without testing.",
 "private-label-pet-toys"),
("wholesalers","Wholesalers & Distributors","Natural Pet Toy Supply for Distributors | VietPaw",
 "Natural Pet Toy Supply for Wholesalers & Distributors",
 "Plan a repeatable assortment with clear specifications, product-level minimums, carton data and rolling demand. Quote the mix you will actually reorder.",
 "export-packed-box.jpg",
 [("Reorder consistency","Use the approved sample, material list, size bands and pack configuration for repeat orders."),
 ("Quantity-based pricing","Request price breaks relevant to your SKU mix instead of applying one universal tier table."),
 ("Supply planning","Share demand by SKU, required dispatch dates and seasonal peaks."),
 ("Receiving checks","Agree carton labels, pack counts and inspection/claim terms before shipment.")],
 [("Assortment","SKU, material, size, quantity and pack format per line"),
 ("Forecast","Confirmed orders separated from non-binding demand estimates"),
 ("Delivery","Required dates, transport mode and destination responsibilities"),
 ("Governance","Version control, material changes and receiving-quality process")],
 "The supplied company material quotes indicative annual capacity, but that does not reserve a production slot. Ask for a plan against your product mix and schedule. Territory or product exclusivity is a separate negotiation and should never be inferred from a volume order.",
 "wholesale-pet-products"),
("startup-brands","Startup Brands","Low-MOQ Pet Toys for Startup Brands | VietPaw",
 "Launch Your First Natural Pet Toy SKU",
 "Start with a manageable product brief and a physical sample. Separate product minimums from branded packaging, then plan the first run around your available capital and sales channel.",
 "dog-lifestyle-chew-1.jpg",
 [("A focused first product","Choose one clear use case and size assortment rather than buying a broad range without demand evidence."),
 ("Sample-first approval","Inspect dimensions, finish, packaging and warnings before bulk production."),
 ("Brand presentation","Discuss labels, wood engraving and practical packaging options."),
 ("Media support","Ask what product photos/video can be provided, with cost and usage permissions confirmed.")],
 [("First SKU","Target pet, intended use, size and material"),
 ("Pilot quantity","Minimum per SKU and a separate box/print minimum"),
 ("Launch assets","Logo, label copy, photos and usage rights"),
 ("Timeline","Sample, artwork, production, transport and launch buffer")],
 "Selected standard products start from 50 pcs per SKU. Private-label runs, custom hang tags, labels and printed boxes start at 500 pcs; laser engraving on suitable coffee wood surfaces is available separately from 50 pcs. 3 free samples. Buyer covers courier. Ask for an itemized quote for custom development, media and packaging before committing your launch budget.",
 "private-label-pet-toys"),
("eco-pet-shops","Eco Pet Shops","Natural Pet Toys for Eco Retailers | VietPaw",
 "A Natural-Material Range with Specific, Supportable Claims",
 "Build a shelf story around what the product actually contains. Choose natural-material formats, check the entire pack and confirm which sourcing statements you can support.",
 "winvn-loofah-growing.png",
 [("Specific material stories","Describe coffee wood or coconut-husk fiber without applying an upcycled claim to every product."),
 ("Packaging transparency","Check paper coatings, bag film, inks, thread and adhesives before saying plastic-free."),
 ("Product suitability","Match the design to the intended pet and use; avoid claims that natural means harmless."),
 ("Import preparation","Have the broker confirm applicable documents and any origin-preference eligibility.")],
 [("Product declaration","Every component, not just the headline material"),
 ("Packaging declaration","Boxes, bags, tags, coatings and moisture protection"),
 ("Claim evidence","Source/reuse support and any relevant disposal test scope"),
 ("Shelf information","Product identity, dimensions, instructions and responsible disposal wording")],
 "Plant-derived, renewable, reused and biodegradable are not interchangeable descriptions. Do not promise a decomposition time or carbon saving without a defined assessment. Natural charcoal as a desiccant does not establish plastic-free wrapping, and a kraft-colored pack may still have coatings.",
 "wholesale-pet-products"),
("pet-brands","Pet Brands","Natural Pet Toy Manufacturing for Pet Brands | VietPaw",
 "A Manufacturing Brief Built Around Your Pet Brand",
 "Develop a natural-material line with defined construction, artwork and approval stages. Protect consistency by treating the sample and specification as part of the brand.",
 "process-laser-engraving.jpg",
 [("Design differentiation","Choose a meaningful change in shape, material or pack; distinguish it from simply adding a logo."),
 ("Specification ownership","Agree who owns supplied drawings, developed designs and any tooling."),
 ("Approval control","Maintain sample, drawing and artwork versions across the product lifecycle."),
 ("Scalable reorders","Review material availability, lead time and packaging supply before increasing volume.")],
 [("Brand brief","Target customer, market, use, positioning and product requirements"),
 ("Development brief","Dimensions, material exclusions, design files and intended claims"),
 ("Approval package","Prototype, full component list, artwork and test/inspection plan"),
 ("Repeat production","Change notices, approved versions and forecast")],
 "Discuss confidentiality before sharing sensitive designs. A request for exclusivity or ownership is not automatically accepted because a product is private labeled. Put the relevant rights, scope, territory and duration in an agreement appropriate to the project.",
 "oem-odm-pet-toy-manufacturing"),
("retail-chains","Retail Chains","Natural Pet Toy Supplier for Retail Chains | VietPaw",
 "Natural Pet Toy Supply for Retail-Chain Rollouts",
 "Prepare a consistent product and vendor information pack before expanding store distribution. Align carton configuration, labeling and delivery windows with the chain's requirements.",
 "warehouse-winvn-boxes.jpg",
 [("Vendor onboarding","Confirm contracting entity, contacts and the retailer's required document set."),
 ("Retail-unit consistency","Control size, packaging dimensions, warnings and barcode artwork."),
 ("Distribution-center handling","Agree master-carton marks, quantities and any required pallet configuration."),
 ("Phased supply","Separate a pilot-store launch from later distribution volumes and dates.")],
 [("Vendor pack","Company details, product specification and agreed reports"),
 ("Unit data","Dimensions, weight, identifiers, pack artwork and instructions"),
 ("Case data","Units/carton, gross weight, dimensions and marking"),
 ("Rollout plan","Store/DC demand, deadlines, inspection and replenishment cycle")],
 "Retailer acceptance is not guaranteed by a generic export-ready claim. Provide the actual vendor manual and list the requirements that need to be checked or quoted. Agree who approves artwork, reports and packing before committing to the rollout calendar.",
 "wholesale-pet-products"),
]

def build(root):
    publish(root,"/solutions/","Sourcing Solutions for Pet Product Buyers | VietPaw",
        "VietPaw sourcing plans for Amazon sellers, distributors, startup brands, pet brands, eco shops and retail chains.",
        "Sourcing Plans for the Way Your Business Buys",
        "The same material can serve different business models. Choose the buyer route that matches your launch, assortment or replenishment needs.",
        [section("Choose your buying context",cards([(label,lede,"/solutions/"+slug+"/") for slug,label,title,h1,lede,img,features,brief,extra,service in SOLUTIONS])),
         section("Keep the product specification at the center",p("Every route begins with a product sample, measurable specification and clear commercial scope. Marketplace, importer and retailer requirements should be part of the brief rather than added after production.")+trust_links(),True)],active="Solutions")
    for slug,label,title,h1,lede,img,features,brief,extra,service in SOLUTIONS:
        sections=[
            section("What your sourcing plan needs to address",cards([(name,desc,"/services/"+service+"/") for name,desc in features],2)),
            section("Build a complete buyer brief",table(["Area","What to provide or confirm"],brief),True),
            section("Make the decision on the right evidence",p(extra)),
            section("From sample to production",terms()+p('<a href="/services/'+service+'/">Review the relevant service</a> and <a href="/how-to-order/">follow the order approval sequence</a>.'),True),
            section("Manufacturer and quality checks",trust_links()+p("Confirm report scope, required inspections and the written handling of non-conforming goods. A process description does not guarantee every future order or market approval."))]
        if slug=="amazon-sellers":
            sections.insert(3,section("Compare pack economics using your own data",
                p(f'Referral, FBA, storage and advertising costs vary by marketplace, category, packaged dimensions and fulfillment program. Use the current <a href="{AMAZON}">Amazon pricing information</a> and the tools for your selling account; this page does not apply one global fee percentage.')+
                p("Compare net sales less product/pack cost, inbound logistics, marketplace charges, advertising and returns. Keep the measurement period, currency, order definition and seller population consistent.")+
                p("An earlier version of this page described a third-party example in our planning material as our own AOV data. It is not presented here as a verified VietPaw client result. The period, marketplace and underlying order export were not supplied.")+
                p("For FBA preparation, you provide the current shipment plan and labeling instructions. We discuss packing and forwarding support against that brief; this does not imply Amazon endorsement, guaranteed acceptance or a guaranteed direct-delivery route."),True))
        if slug=="eco-pet-shops":
            sections.insert(3,section("Review the claim before it goes on a shelf",
                p('<a href="/sustainability/">See our sustainability and packaging boundaries</a>. Use the <a href="/collections/plastic-free/">plastic-free sourcing checklist</a> to turn a broad requirement into a component-level brief.')))
        publish(root,"/solutions/"+slug+"/",title,lede,h1,lede,sections,
            active="Solutions",image="/assets/img/"+img,
            trail=[("Home","/"),("Solutions","/solutions/"),(label,None)],
            faqs=[("Can I request a sample before deciding the range?", "Yes. Tell us which product, size and pack you want to evaluate. Availability, sample terms and courier costs are confirmed first."),
                  ("What should I send for a useful quote?", "Send quantities per SKU, destination, required timing and the packaging or development brief. Attach the applicable retailer or marketplace requirements if available.")])
    # A review-ready hub, deliberately excluded from indexing until a real case is authorized.
    publish(root,"/case-studies/","Case Study Evidence: Publication Checklist | VietPaw",
        "Pre-publication case study framework. No verified customer result or performance metric is asserted on this draft page.",
        "Case Studies — Evidence Before Publication",
        "This section is prepared for future, authorized buyer case studies. No verified customer outcome is currently published here.",
        [section("What a publishable case must establish",ul([
            "Buyer permission and an agreed level of anonymization.",
            "Project period, destination, product specification and scope of the supplied work.",
            "Sample, production, inspection and shipment evidence linked to the same project.",
            "Measurement definitions and source records for any numerical result.",
            "Limitations, including factors not controlled by the manufacturer."])),
         section("Available now",p('Review <a href="/factory/">production information</a>, <a href="/quality-control/">quality planning</a> and <a href="/certifications/">document scope</a>. Discuss appropriate project references directly with the sales team.'))],
        noindex=True)
